services:
  - type: web
    name: cryptosignai-miniapp
    env: node
    plan: free
    repo: https://github.com/themagician1970/cryptosignai-telegram-miniapp
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        value: 8053605696:AAEkjm-7Uj8DTpvgjIaVSTbESxxgW2NJdng
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    branch: master
